pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t johnhope55/example-webserver .

test:
  image: docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker run <username>/example-webserver /test.sh